[mypy]
python_version = 3.12
strict = True
warn_unused_configs = True
exclude = (?x)(^tests/)

[mypy-jose.*]
ignore_missing_imports = True

[mypy-passlib.*]
ignore_missing_imports = True

[mypy-wikipedia]
ignore_missing_imports = True
